-- MySQL Script generated by MySQL Workbench
-- Sun 19 Jul 2020 12:23:14 PM -04
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliente` DEFAULT CHARACTER SET utf8 ;
USE `cliente` ;

-- -----------------------------------------------------
-- Table `cliente`.`acceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`acceso` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(10) NULL,
  `clave` VARCHAR(10) NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`persona` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `cedula` VARCHAR(12) NOT NULL,
  `direccion` VARCHAR(200) NULL,
  `telefono` VARCHAR(45) NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`codigo`, `idusuario`),
  INDEX `fk_persona_ingreso1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_persona_ingreso1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `cliente`.`acceso` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`mercancia` (
  `idmercancia` INT NOT NULL AUTO_INCREMENT,
  `mercancia` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idmercancia`, `idusuario`),
  INDEX `fk_mercancia_ingreso1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_mercancia_ingreso1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `cliente`.`acceso` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`pedido` (
  `idfactura` INT NOT NULL,
  `codigo` INT NOT NULL,
  `idmercancia` INT NOT NULL,
  `cantidad` INT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idfactura`, `codigo`, `idmercancia`, `idusuario`),
  INDEX `fk_pedido_persona_idx` (`codigo` ASC) VISIBLE,
  INDEX `fk_pedido_mercancia1_idx` (`idmercancia` ASC) VISIBLE,
  INDEX `fk_pedido_ingreso1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_persona`
    FOREIGN KEY (`codigo`)
    REFERENCES `cliente`.`persona` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_mercancia1`
    FOREIGN KEY (`idmercancia`)
    REFERENCES `cliente`.`mercancia` (`idmercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_ingreso1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `cliente`.`acceso` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
