-- MySQL Script generated by MySQL Workbench
-- Thu Jul  2 13:46:49 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cliente
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cliente` DEFAULT CHARACTER SET utf8 ;
USE `cliente` ;

-- -----------------------------------------------------
-- Table `cliente`.`persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`persona` (
  `cedula` VARCHAR(11) NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `edad` INT NULL,
  PRIMARY KEY (`cedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`mercancia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`mercancia` (
  `idmercancia` INT NOT NULL AUTO_INCREMENT,
  `mercancia` VARCHAR(45) NULL,
  `precio` DOUBLE NULL,
  PRIMARY KEY (`idmercancia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cliente`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cliente`.`pedido` (
  `idfactura` INT NOT NULL AUTO_INCREMENT,
  `cedula` VARCHAR(11) NOT NULL,
  `idmercancia` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idfactura`, `cedula`, `idmercancia`),
  INDEX `fk_pedido_persona_idx` (`cedula` ASC) ,
  INDEX `fk_pedido_mercancia1_idx` (`idmercancia` ASC) ,
  CONSTRAINT `fk_pedido_persona`
    FOREIGN KEY (`cedula`)
    REFERENCES `cliente`.`persona` (`cedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_mercancia1`
    FOREIGN KEY (`idmercancia`)
    REFERENCES `cliente`.`mercancia` (`idmercancia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
